Adding sorting algorithms
TheAlgorithms/Nim pull request #29
Opened 2023-06-18 03:22 UTC by SatinWuker

Algorithms Nim seems like a very new project with few contributions. I added two new sorting algorithms, Insertion sort, and Bubble sort. I will try to contribute more algorithms to this project, and I desire to see this project grow!

2023-06-18 08:20 UTC, dlesnoff commented
Please have a look at PR #22 that I made but is a draft right now due to the lack of comments.
I appreciate that you made a lot of comments and provided per file tests.
Precise Best case time complexity rather than just best time complexity.

2023-06-18 11:00 UTC, SatinWuker commented
> Please have a look at PR #22 that I made but is a draft right now due to the lack of comments. I appreciate that you made a lot of comments and provided per file tests. Precise Best case time complexity rather than just best time complexity.

@dlesnoff Nice to meet you, and I am really sorry that I did not see your pull request because I made my PR on a train so I wanted to submit it as quickly as possible and did not check if there are similar PRs. However, will this still be merged because of your previous pull request? If not, I will restore my fork and start working on other algorithms.

2023-06-18 14:16 UTC, dlesnoff requested changes
Thanks for your kind first contribution, but I think that many issues must be addressed before merging them. I plan to merge your implementation when these are addressed.

In general, the comments duplicates what a developer sees from the code.
They should rather give insights on the «why» of the algorithm. Why two for loops?
Which part of the bubble sort corresponds to a bubble? What can be guaranteed after a «bubble» (a pass) on the list (give invariants)?

Most importantly, it seems like you have overlooked the CONTRIBUTING.md document that we have carefully written to give first contributors an idea of the general structure of a program.
The when isMainModule is important for a file to be shipped inside a big project without messing the imports.

You confused `high(arr)` for `len(arr)`.

The tests do not reflect the genericity of the algorithm. Even if the procedure has been written for integers only, there should at least be a zero and negative numbers in them. Some small random tests would be very much appreciated. Your tests are very similar and could be templated too.

2023-06-18 14:16 UTC, dlesnoff commented on sorting/insertion_sort.nim
> +      j -= 1
Another Nim's syntax sugar that I like. You can resolve this conversation if you do not like this notation.
```suggestion
     dec j
```

2023-06-18 14:16 UTC, dlesnoff commented on sorting/insertion_sort.nim
> +## Test
Same comments as above.

2023-06-19 01:44 UTC, closed without merging

2023-06-19 02:14 UTC, SatinWuker commented
I guess I should not do any duplicated work, and I will move on from sorting algorithms to searching algorithms as you are almost done with sortings! Thank you for the problems you pointed out, it really helps me, and I will follow the contribution guidelines, write better comments, and take notice of the code I am writing.