Fix linear search
TheAlgorithms/Nim pull request #33
Opened 2023-06-20 12:41 UTC by dlesnoff

Fix #31. Run nimpretty directly on the file.

2023-06-20 20:53 UTC, ZoomRmc reviewed
@beef331 is right. Since the logic has already been changed to iterate the array in ascending manner, better to change the default to `Natural(0)`.

I would also removed the custom type aliases, it trades better locality for shorter lines (that still wrap), so no win as I see it.

What's the reason for changing the `func` to `proc`?

2023-06-20 21:14 UTC, ZoomRmc approved these changes

2023-06-21 01:27 UTC, SatinWuker requested changes
Maybe just do this, to avoid confusion. Overall nim prettify has done illustriously 👍 
And indeed, adding type definition to `Natural` and `Option[Natural]` looks redundant and verbose. well done!

2023-06-21 01:27 UTC, SatinWuker commented on searches/linear_search.nim
>      test "Search in a string array matching with a string matching value":
Since you added `@` on line 82, I would do 
```suggestion
    test "Search in a string sequence matching with a string matching value":
```

2023-06-21 06:31 UTC, pietroppeter commented
As a note on linearSearch I think current version is buggy in case of arrays with negative indices (which are allowed for open array), see https://play.nim-lang.org/#ix=4yJs

```nim
import std/options

func linearSearch*[T](arr: openArray[T], key: T): Option[Natural] =
  # key is the value we are searching for in the array.
  for i, val in arr.pairs():
    if val == key:
      return some(Natural(i))
  none(Natural) # `key` not found

type
  NegIdxArray = array[-1 .. 1, int]

let
  a: NegIdxArray = [1,2,3]

echo linearSearch(a, 1) # some(0)
```

Correct answer should be `some(-1)`

2023-06-21 06:38 UTC, dlesnoff commented
@pietroppeter This is also the case for any array with a custom starting index, isn't it?

2023-06-21 07:37 UTC, beef331 commented
This is the case for any array that does not start at 0 or use a data type that starts as 0, it's probably best to just have an `openArray` and a `array[Idx, T]` search.

2023-06-21 07:41 UTC, dlesnoff commented
Having two functions for each would be contrary to the DRY - Don't Repeat Yourself principle. That feels like unnecessary duplicate code for me.

2023-06-21 07:54 UTC, beef331 commented
Sure but they have to be  specialized. `array[bool, T]` or `array[MyEnum, T]` gets `Option[Natural]` which requires a type conversion back to index type by the user. The most reusable that should work for all types and the least amount of DRY breaking is as follows: 

```nim

func linearSearchImpl[T](arr: openArray[T], key: T): int =
  for i, val in arr.pairs():
    if val == key:
      return i
  -1
  
func linearSearch*[T](arr: openArray[T], key: T): Option[Natural] =
  let val = linearSearchImpl(arr, key)
  if val >= 0:
    some(Natural(val))
  else:
    none(Natural)
    
func linearSearch*[Idx, T](arr: array[Idx, T], key: T): Option[Idx] =
  let val = linearSearchImpl(arr, key)
  if val >= 0:
    some(Idx(ord(arr.low) + val))
  else:
    none(Idx)  
```

2023-06-21 08:53 UTC, pietroppeter commented
Ah, I did not know that openarray did not support low and high. checked here indeed it has 0 as low always for openarray: https://play.nim-lang.org/#ix=4yJD

2023-06-21 08:55 UTC, beef331 commented
Well they support it as you've shown, but `openArray` is explicitly a type erasure so yea it loses the source type information. It's implemented as a `ptr T, len` afterall.

2023-06-21 10:34 UTC, dlesnoff commented
@beef331 I do not want to merge your modifications. It adds much complexity to handle an often superfluous feature of array reindexing. I prefer to keep the implementation as simple as possible.

While one of our implementation's goals is « easy integration in one's code project », our primary goal is pedagogical algorithm teaching. I will use your code if indexed arrays reveal to be needed in the future.

2023-06-21 12:51 UTC, ZoomRmc commented
> @beef331 I do not want to merge your modifications. It adds much complexity to handle an often superfluous feature of array reindexing. I prefer to keep the implementation as simple as possible.
> 
In this case it would be nice to document that the function does return the absolute index and not a corresponding index value for range/enum-indexed arrays.

2023-06-21 13:01 UTC, ZoomRmc requested changes

2023-06-21 13:01 UTC, ZoomRmc commented on searches/linear_search.nim
>    # key is the value we are searching for in the array.
```suggestion
  ## Searches for the `key` in `arr` and returns its absolute index (counting from 0)
  ## in the array.
  ## .. Note:: For arrays indexed with a range type or an enum the returned value
  ##  may not be consistent with the indexing of the initial array.
```

2023-06-21 13:01 UTC, ZoomRmc commented on searches/linear_search.nim
>    # Recursive calls replace the for loop.
```suggestion
  ## Searches for the `key` in `arr` and returns its absolute index (counting from 0)
  ## in the array. Search is performed in a recursive manner.
  ## .. Note:: For arrays indexed with a range type or an enum the returned value
  ##  may not be consistent with the indexing of the initial array.
  # Recursive calls replace the `for` loop in `linearSearch`.
```

2023-06-21 13:44 UTC, dlesnoff commented on searches/linear_search.nim
>    # key is the value we are searching for in the array.
Thanks for the comments suggestions.

2023-06-23 20:20 UTC, Panquesito7 approved these changes
Approving to allow the merge. Thanks. 👍

2023-06-23 20:22 UTC, merged