docs: add missing `#`
TheAlgorithms/Nim pull request #50
Opened 2023-06-28 13:50 UTC by vil02

This PR adds a missing `#` in the `module-level documentation` in changed `*.nim` files. It not only adapts these files to the [contributing guidelines](https://github.com/vil02/Nim/blob/17c4c39a31e2e0e56110d9117ba2c5d4d8916e20/CONTRIBUTING.md) but also removes the warnings when executing `nim r .scripts/directory.nim`.

2023-06-28 14:07 UTC, ZoomRmc requested changes

2023-06-28 14:47 UTC, ZoomRmc approved these changes

2023-06-29 11:46 UTC, dlesnoff commented on maths/arc_length.nim
> +## Arc Length of a Circle
I think I talked about it in #38.
There are other definitions of Arc Length, that are much more generic that can be computed for any curve besides a circle.
But fine for now.

2023-06-29 11:46 UTC, dlesnoff approved these changes

2023-06-29 11:47 UTC, merged